version: 2.1

parameters:
  BUILD_COMMAND:
    type: string
    default: "npm run build"
  BUILD_DIR:
    type: string
    default: ""
  ENVIRONMENT:
    type: string
    default: "default"
    enum: ["default", "development", "staging", "sepolia-staging"]
  ENVIRONMENT_VARIABLES:
    type: string
    default: ""
  GITHUB_ACCESS_TOKEN:
    type: string
    default: ""
  NODE_VERSION:
    type: string
    default: "22.4.1"
  ONE_CLICK_SERVER_URL:
    type: string
    default: ""
  OUTPUT_DIR:
    type: string
    default: ""
  PACKAGE_INSTALL_COMMAND:
    type: string
    default: "export NODE_OPTIONS=--openssl-legacy-provider && npm install"
  REF:
    type: string
    default: ""
  REPOSITORY:
    type: string
    default: "https://github.com/thales-markets/thales-sport-markets"
  S3_URL:
    type: string
    default: ""
  SECRETS:
    type: string
    default: ""
  SOURCE_TYPE:
    type: string
    default: "github"
  CI_TRIGGER:
    type: boolean
    default: true

jobs:
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Check CI_TRIGGER
          command: |
            if [ "<< pipeline.parameters.CI_TRIGGER >>" != true ]; then
              echo "CI_TRIGGER is not true. Exiting with success."
              circleci-agent step halt
            else
              echo "CI_TRIGGER is true. Continuing with the workflow."
            fi

      - run:
          name: Install AWS CLI
          command: |
            if ! command -v aws &> /dev/null; then
              sudo apt-get update && sudo apt-get install -y awscli
            fi

      - run:
          name: Install NVM and Node.js
          command: |
            if [ ! -d "$HOME/.nvm" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            fi
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install << pipeline.parameters.NODE_VERSION >>
            nvm use << pipeline.parameters.NODE_VERSION >>
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV

      - run:
          name: Install Dependencies
          command: |
            npm install node-forge

      - run:
          name: Create Decryption Script
          command: |
            echo "const forge = require('node-forge');" > ~/project/decrypt.js
            echo "const fs = require('fs');" >> ~/project/decrypt.js
            echo "" >> ~/project/decrypt.js
            echo "function decryptData(encryptedData) {" >> ~/project/decrypt.js
            echo "  const privateKeyPem = Buffer.from(process.env.BASE64_ENCODED_PRIVATE_KEY, 'base64').toString('utf8');" >> ~/project/decrypt.js
            echo "  const privateKey = forge.pki.privateKeyFromPem(privateKeyPem);" >> ~/project/decrypt.js
            echo "  const decodedData = forge.util.decode64(encryptedData);" >> ~/project/decrypt.js
            echo "  return privateKey.decrypt(decodedData, 'RSA-OAEP', {" >> ~/project/decrypt.js
            echo "    md: forge.md.sha256.create()," >> ~/project/decrypt.js
            echo "    mgf1: { md: forge.md.sha1.create() }" >> ~/project/decrypt.js
            echo "  });" >> ~/project/decrypt.js
            echo "}" >> ~/project/decrypt.js
            echo "" >> ~/project/decrypt.js
            echo "const input = process.argv[2];" >> ~/project/decrypt.js
            echo "try {" >> ~/project/decrypt.js
            echo "  const parsedJson = JSON.parse(input);" >> ~/project/decrypt.js
            echo "  const decryptedJson = Object.keys(parsedJson).reduce((acc, key) => {" >> ~/project/decrypt.js
            echo "    acc[key] = decryptData(parsedJson[key]);" >> ~/project/decrypt.js
            echo "    return acc;" >> ~/project/decrypt.js
            echo "  }, {});" >> ~/project/decrypt.js
            echo "  console.log(JSON.stringify(decryptedJson));" >> ~/project/decrypt.js
            echo "} catch (e) {" >> ~/project/decrypt.js
            echo "  // If parsing fails, assume it's a single encrypted token" >> ~/project/decrypt.js
            echo "  console.log(decryptData(input));" >> ~/project/decrypt.js
            echo "}" >> ~/project/decrypt.js

      - run:
          name: Decode secrets and environment variables
          command: |
            touch ~/project/combined_env_vars.txt
            if [ -n "<< pipeline.parameters.SECRETS >>" ]; then
              echo "Decoding secrets..."
              DECRYPTED_JSON=$(node ~/project/decrypt.js '<< pipeline.parameters.SECRETS >>')
              if [[ $DECRYPTED_JSON == {* ]]; then
                echo "$DECRYPTED_JSON" | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' > ~/project/decrypted_secrets.txt
              else
                echo "DECRYPTED_SECRET=$DECRYPTED_JSON" > ~/project/decrypted_secrets.txt
              fi
              source <(sed 's/^/export /' ~/project/decrypted_secrets.txt)
              cat ~/project/decrypted_secrets.txt >> ~/project/combined_env_vars.txt
            fi

            if [ -n "<< pipeline.parameters.ENVIRONMENT_VARIABLES >>" ]; then
              echo "Processing environment variables..."
              echo "<< pipeline.parameters.ENVIRONMENT_VARIABLES >>" > ~/project/environment_variables.txt
              source <(sed 's/^/export /' ~/project/environment_variables.txt)
              cat ~/project/environment_variables.txt >> ~/project/combined_env_vars.txt
            fi

      - when:
          condition:
            or:
              - equal: ["<< pipeline.parameters.SOURCE_TYPE >>", "url"]
              - equal: ["<< pipeline.parameters.SOURCE_TYPE >>", "github"]
          steps:
            - run:
                name: Clone Repository
                command: |
                  REPO_URL="<< pipeline.parameters.REPOSITORY >>"
                  REPO_PATH=$(echo $REPO_URL | sed 's#https://github.com/##')

                  if [ -n "<< pipeline.parameters.GITHUB_ACCESS_TOKEN >>" ] && [ -n "$BASE64_ENCODED_PRIVATE_KEY" ]; then
                    ENCRYPTED_TOKEN="<< pipeline.parameters.GITHUB_ACCESS_TOKEN >>"
                    DECRYPTED_TOKEN=$(node ~/project/decrypt.js "$ENCRYPTED_TOKEN")
                    git clone "https://$DECRYPTED_TOKEN@github.com/${REPO_PATH}" ~/project/repository
                    unset DECRYPTED_TOKEN
                  else
                    git clone "$REPO_URL" ~/project/repository
                  fi

                  cd ~/project/repository
                  if [ -n "<< pipeline.parameters.REF >>" ]; then
                    git checkout "<< pipeline.parameters.REF >>"
                  else
                    echo "No branch specified, staying on default branch."
                  fi

            - setup_remote_docker

            - run:
                name: Prepare Build Environment
                command: |
                  cat \<< EOF > Dockerfile
                  FROM node:<< pipeline.parameters.NODE_VERSION >>-slim
                  WORKDIR /app
                  EOF
                  docker build -t build-env .

            - run:
                name: Run Build in Controlled Environment
                command: |
                  docker run --rm \
                    --env-file ~/project/combined_env_vars.txt \
                    -v ~/project/repository:/app \
                    -w "/app/<< pipeline.parameters.BUILD_DIR >>" \
                    --memory=4g \
                    --cpus=2 \
                    --network host \
                    build-env \
                    /bin/sh -c '
                      set -e
                      << pipeline.parameters.PACKAGE_INSTALL_COMMAND >>
                      timeout 30m << pipeline.parameters.BUILD_COMMAND >>
                    '

      - when:
          condition:
            equal: ["upload", "<< pipeline.parameters.SOURCE_TYPE >>"]
          steps:
            - run:
                name: Download and Extract from S3
                command: |
                  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                  aws configure set default.region $AWS_REGION

                  if [ "<< pipeline.parameters.ENVIRONMENT >>" == "development" ]; then
                    S3_BUCKET_NAME=$AWS_S3_USER_UPLOADS_BUCKET_NAME_DEV
                  elif [ "<< pipeline.parameters.ENVIRONMENT >>" == "staging" ]; then
                    S3_BUCKET_NAME=$AWS_S3_USER_UPLOADS_BUCKET_NAME_SEPOLIA
                  elif [ "<< pipeline.parameters.ENVIRONMENT >>" == "staging-sepolia" ]; then
                    S3_BUCKET_NAME=$AWS_S3_USER_UPLOADS_BUCKET_NAME_SEPOLIA_STAGING
                  else
                    echo "Invalid / default environment specified."
                    exit 1
                  fi

                  S3_PATH="s3://$S3_BUCKET_NAME/$(basename "<< pipeline.parameters.S3_URL >>")"
                  aws s3 cp $S3_PATH ~/project/repository --recursive

                  if [ $(find ~/project/repository -mindepth 1 -maxdepth 1 -type d | wc -l) -eq 1 ] && [ $(find ~/project/repository -mindepth 1 -maxdepth 1 -type f | wc -l) -eq 0 ]; then
                    extracted_folder=$(find ~/project/repository -mindepth 1 -maxdepth 1 -type d)
                    mv "$extracted_folder"/* ~/project/repository/
                    rmdir "$extracted_folder"
                  fi

      - run:
          name: Check for index.html
          working_directory: ~/project/repository
          command: |
            OUTPUT_DIR=.
            if [ -n "<< pipeline.parameters.OUTPUT_DIR >>" ]; then
              OUTPUT_DIR="<< pipeline.parameters.OUTPUT_DIR >>"
            fi
            if [ -f "$OUTPUT_DIR/index.html" ]; then
              echo "index.html found in $OUTPUT_DIR"
            else
              echo "Error: index.html not found in $OUTPUT_DIR"
              exit 1
            fi

      - run:
          name: Create Earthfast Bundle
          working_directory: ~/project
          command: |
            OUTPUT_DIR="<< pipeline.parameters.OUTPUT_DIR >>"
            BUNDLE_PATH="${OUTPUT_DIR:+repository/$OUTPUT_DIR}"
            BUNDLE_PATH="${BUNDLE_PATH:-repository}"

            bundle_filename="$(npx --package=earthfast-cli@0.7.1 --yes earthfast bundle create earthfast-bundle "$BUNDLE_PATH")"
            checksum="$(npx --package=earthfast-cli@0.7.1 --yes earthfast bundle checksum $bundle_filename)"

            echo $checksum > ~/project/repository/checksum
            echo "Bundle Filename: $bundle_filename"
            echo "Checksum: $checksum"

      - store_artifacts:
          path: earthfast-bundle.tgz
      - store_artifacts:
          path: ~/project/repository/checksum

      - run:
          name: Notify One Click Server
          when: always
          command: |
            ONE_CLICK_SERVER_URL="<< pipeline.parameters.ONE_CLICK_SERVER_URL >>"
            PIPELINE_ID="<< pipeline.id >>"
            CHECKSUM_PATH="$HOME/project/repository/checksum"

            if [ -f "$CHECKSUM_PATH" ]; then
              CHECKSUM=$(cat "$CHECKSUM_PATH")
              STATUS="success"
              BUNDLE_URL="https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/earthfast-bundle.tgz"
            else
              STATUS="failure"
            fi

            DATA='{"checksum":"'"$CHECKSUM"'","bundleUrl":"'"$BUNDLE_URL"'","pipelineId":"'"$PIPELINE_ID"'","status":"'"$STATUS"'"}'

            SIGNATURE=$(echo -n "$DATA" | openssl dgst -sha256 -hmac "$CIRCLECI_WEBHOOK_SECRET" | sed 's/^.* //')
            FULL_URL="${ONE_CLICK_SERVER_URL}/circleci/notify"

            curl -X POST \
              -H "Content-Type: application/json" \
              -H "x-circleci-signature: $SIGNATURE" \
              -d "$DATA" \
              "$FULL_URL"

workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish
