name: Merge dev to main

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Push dev to main
      run: |
        git push origin dev:main
