name: Merge dev to main

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Push dev to main
      run: |
        git fetch --all
        git pull origin main
        git checkout dev
        git pull origin main
        git push origin dev:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
