name: Mirror to Private Repository

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - '*'  # Trigger on pushes to any branch
      - dm-mirror-private-repo

jobs:
  mirror_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Push to private repository
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        # Configure Git
        git config user.name github-actions
        git config user.email github-actions@github.com

        # Debug: Print Git version
        git --version

        # Debug: Print target repo URL (masking the token)
        echo "Target repo: https://github.com/earthfast/dashboard-runner-private.git"

        # Debug: Check if GH_PAT is set
        if [ -z "$GH_TOKEN" ]; then
          echo "Error: GH_PAT is not set"
          exit 1
        fi

        # Clone the source repository
        git clone --mirror https://${GH_TOKEN}@github.com/earthfast/dashboard-runner.git source-repo
        cd source-repo

        # Push branches to the private repository
        git push --prune https://${GH_TOKEN}@github.com/earthfast/dashboard-runner-private.git +refs/heads/*:refs/heads/*

        # Push tags to the private repository
        git push --prune https://${GH_TOKEN}@github.com/earthfast/dashboard-runner-private.git +refs/tags/*:refs/tags/*

        echo "Repository mirrored successfully!"

        # Debug: Check GitHub API rate limit
        curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/rate_limit